name: Reusable CI for npm

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: 24
      build:
        required: false
        type: string
        default: npm run build
      test:
        required: false
        type: string
        default: npm run test

permissions:
  contents: read

jobs:
  ci-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: ${{ inputs.build }}

      - name: Test
        run: ${{ inputs.test }}
